---
- name: Setup Olive Art Server
  hosts: web
  become: yes

  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Olive Art website
      copy:
        src: ../website/index.html
        dest: /var/www/html/index.html
        mode: '0644'
